//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedDocuments
    {
        public int Id { get; set; }
        public string OrderName { get; set; }
        public System.DateTime DateOfOrderOutcoming { get; set; }
        public bool Sign { get; set; }
        public string Role { get; set; }
    
        public virtual Order_ Order_ { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
