//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyingPracticeEntities : DbContext
    {
        private static StudyingPracticeEntities _context;   ///Контекст данных

        public StudyingPracticeEntities()
            : base("name=StudyingPracticeEntities")
        {
        }

        public static StudyingPracticeEntities GetContext()     ///Метод GetContext, позволяющий возвращать данные из базы данных
        {
            if (_context == null)       ///Если контекст пуст
                _context = new StudyingPracticeEntities();      ///Создание нового экземпляра контекста
            return _context;        ///Возврат контекста
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommonEmployee> CommonEmployee { get; set; }
        public virtual DbSet<Event_> Event_ { get; set; }
        public virtual DbSet<IssuedDocuments> IssuedDocuments { get; set; }
        public virtual DbSet<Order_> Order_ { get; set; }
        public virtual DbSet<OutgoingCorrespondent> OutgoingCorrespondent { get; set; }
        public virtual DbSet<Supervisor> Supervisor { get; set; }
    }
}
